dotpcap/sharppcap

README.md
Simplified AppVeyor badge and also added a NuGet one.
=> Revised badges.

Examples/CreatingCaptureFile/CreatingCaptureFile.csproj, Examples/Example1.IfList/Example01.IfList.csproj, Examples/Example10.SendQueue/Example10.SendQueue.csproj, Examples/Example11.Statistics/Example11.Statistics.csproj, Examples/Example12.PacketManipulation/Example12.PacketManipulation.csproj, Examples/Example2.ArpResolve/Example02.ArpResolve.csproj, Examples/Example3.BasicCap/Example03.BasicCap.csproj, Examples/Example4.BasicCapNoCallback/Example04.BasicCapNoCallback.csproj, Examples/Example5.PcapFilter/Example05.PcapFilter.csproj, Examples/Example6.DumpTCP/Example06.DumpTCP.csproj, Examples/Example9.SendPacket/Example09.SendPacket.csproj, Examples/MultipleFiltersOnDevice/MultipleFiltersOnDevice.csproj, Examples/NpcapRemoteCapture/NpcapRemoteCapture.csproj, Examples/QueuingPacketsForBackgroundProcessing/QueuingPacketsForBackgroundProcessing.csproj, Examples/ReadingCaptureFile/ReadingCaptureFile.csproj, Examples/WakeOnLan/WakeOnLan.csproj, Examples/WinformsExample/Properties/AssemblyInfo.cs, Examples/WinformsExample/WinformsExample.csproj, SharpPcap/SharpPcap.csproj, Test/Test.csproj
This will allow using `dotnet build` on the projects and make them more future proof
Tool used https://github.com/hvanbakel/CsprojToVs2017
=> Migrate csproj files to new format

.appveyor.yml, .circleci/config.yml, .circleci/install.sh, .config/travis/test.sh, .travis.yml, Test/Test.csproj, azure-pipelines.yml, codecov.yml
All configuration code wise has been done here, see https://github.com/kayoub5/sharppcap/pull/3 of how it would look like if Codecov in activated in this repo
=> Coverage with Codecov

README.md
=> README.md - Add codecov badge

Examples/CreatingCaptureFile/Program.cs, Examples/Example3.BasicCap/Program.cs, Examples/NpcapRemoteCapture/Program.cs, README.md, SharpPcap/AuthenticationTypes.cs, SharpPcap/ICaptureDevice.cs, SharpPcap/LibPcap/CaptureFileReaderDevice.cs, SharpPcap/LibPcap/CaptureFileWriterDevice.cs, SharpPcap/LibPcap/LibPcapLiveDevice.cs, SharpPcap/LibPcap/PcapDevice.cs, SharpPcap/Npcap/NpcapDevice.cs, SharpPcap/RemoteAuthentication.cs, SharpPcap/WinDivert/WinDivertDevice.cs, Test/RemotePcapTests.cs
I screwed up the last merge, it went from cmm_remote_2 to cmm_remote, this is me recreating the cmm_remote_2 branch so I can push it.
=> Cmm testbranch

SharpPcap/DeviceConfiguration.cs, SharpPcap/LibPcap/CaptureFileReaderDevice.cs, SharpPcap/LibPcap/CaptureFileWriterDevice.cs, SharpPcap/LibPcap/LibPcapLiveDevice.cs, SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs, SharpPcap/LibPcap/PcapDevice.cs, SharpPcap/LibPcap/PcapUnmanagedStructures.cs, SharpPcap/PcapError.cs, Test/CaptureFileWriterDeviceTest.cs, Test/PcapDeviceTest.cs
Nothing fancy, just trying to reduce the number of ifs
=> Simplify Configure calls

.circleci/config.yml, SharpPcap/LibPcap/LibPcapSafeNativeMethods.Resolver.cs, SharpPcap/Statistics/StatisticsDevice.cs, Test/DeviceFixture.cs, Test/RemotePcapTests.cs
=> Check different Libpcap installations methods

SharpPcap/LibPcap/LibPcapSafeNativeMethods.Resolver.cs, SharpPcap/LibPcap/NativeLibraryHelper.cs
=> Use NativeLibrary.Load instead of dlopen

SharpPcap/LibPcap/LibPcapSafeNativeMethods.Encoding.cs, SharpPcap/LibPcap/LibPcapSafeNativeMethods.Interop.cs, SharpPcap/LibPcap/LibPcapSafeNativeMethods.Resolver.cs, SharpPcap/LibPcap/PcapDevice.cs, SharpPcap/Pcap.cs, SharpPcap/PcapClock.cs, SharpPcap/SharpPcap.csproj, Test/CaptureFileReaderDeviceTest.cs, Test/Statistics/StatisticsDeviceTest.cs
=> Auto detect string encoding used by Libpcap

SharpPcap/WinDivert/WinDivertAddress.cs, SharpPcap/WinDivert/WinDivertDevice.cs, SharpPcap/WinDivert/WinDivertNative.cs
Pending reply on https://github.com/basil00/Divert/issues/282 to finish implementation 
Partially resolves #273
=> Use WinDivertRecvEx

SharpPcap/LibPcap/PcapInterface.cs, SharpPcap/LibPcap/WindowsNativeMethods.cs
=> Better FriendlyName detection in Windows

Test/MemorySafetyTests.cs, Test/TestHelper.cs
@chmorgan could you review this first, so that we don't have false positives in other PRs?
=> Disable DisposeDuringCapture on old Libpcap

.semaphore/semaphore.yml, SharpPcap/SharpPcap.csproj, Test/DeviceFixture.cs, Test/TestHelper.cs
@chmorgan you just need a free semaphoreci.com account, the configuration is already tested.
=> Set up semaphore

.appveyor.yml, Examples/WinpkFilterExample/Program.cs, Examples/WinpkFilterExample/WinpkFilterExample.csproj, SharpPcap.sln, SharpPcap/WinpkFilter/AdapterMode.cs, SharpPcap/WinpkFilter/AdapterModes.cs, SharpPcap/WinpkFilter/DriverHandle.cs, SharpPcap/WinpkFilter/EthRequest.cs, SharpPcap/WinpkFilter/HardwarePacketFilters.cs, SharpPcap/WinpkFilter/IntermediateBuffer.cs, SharpPcap/WinpkFilter/Kernel32.cs, SharpPcap/WinpkFilter/NativeMethods.cs, SharpPcap/WinpkFilter/PacketSource.cs, SharpPcap/WinpkFilter/TcpAdapterList.cs, SharpPcap/WinpkFilter/WinpkFilterDevice.cs, SharpPcap/WinpkFilter/WinpkFilterDriver.cs, SharpPcap/WinpkFilter/WinpkFilterHeader.cs, Test/TestHelper.cs, Test/WebHelper.cs, Test/WinDivert/WinDivertDeviceTest.cs, Test/WinpkFilter/WinpkFilterDeviceTest.cs, azure-pipelines.yml, scripts/install-winpkfilter.ps1
Add support for the WinpkFilter from https://www.ntkernel.com/windows-packet-filter/
=> Add support for WinpkFilter

SharpPcap/LibPcap/PcapDevice.cs
=> Prevent Access Violation inside PacketHandler

.github/workflows/dotnet-core.yml
Solution for https://github.com/brandedoutcast/publish-nuget/issues/58
=> Use alirezanet/publish-nuget

scripts/Install-npcap.ps1
@chmorgan I disabled using Npcap OEM key since it's not working, when you have time please double check it and revert this PR.
=> Disable Npcap OEM until Chris fix them.

.circleci/config.yml, scripts/install-dotnet.sh
See https://circleci.com/blog/ubuntu-14-16-image-deprecation/
Resolves #356
=> Remove Ubuntu 16.04

scripts/install-winpkfilter.ps1
See https://ci.appveyor.com/project/chmorgan/sharppcap/builds/43471409/job/0pkofwd1yi3ayhjr
=> Fix flaky winpkfilter install in appveyor

SharpPcap/LibPcap/PcapHeader.cs, SharpPcap/LibPcap/SendQueue.cs, Test/MemorySafetyTests.cs, Test/SendQueueTest.cs
=> Fix time calculation in SendQueue

azure-pipelines.yml
CI of WinPcap broken, `choco install -y winpcap` no longer works.
=> Remove WinPcap CI
