SharpPcap/LibPcap/PcapDevice.cs

This static method should help Linq users who need IEnumerables, and those who like to process packets using the foreach statement.

Added PcapDevice.GetSequence for Linq, foreach, and  extension methods

---

SharpPcap/ICaptureDevice.cs
SharpPcap/LibPcap/CaptureFileReaderDevice.cs
SharpPcap/LibPcap/CaptureFileWriterDevice.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/LibPcap/PcapDevice.cs
SharpPcap/MonitorMode.cs
SharpPcap/SharpPcap.csproj

This PR addresses https://github.com/chmorgan/sharppcap/issues/27, adding support for setting monitor mode when opening an adapter. When used against Npcap or another implementation of LibPcap which supports it, this allows you to capture 802.11 packets.
An overload of the Open method has been added to ICaptureDevice which exposes the monitor_mode option. The underlying implementation of Open has been rewritten to use the more advanced procedure of creating, configuring, and then activating an adapter, and the simpler methods have all been changed to chain into it.
Because getting the Link type can only be done when an adapter is Active (rather than merely created/opened), the Link type caching has been moved from the Open setter to a new Active setter.

Add support for setting monitor mode when opening an adapter

---

SharpPcap/LibPcap/PcapHeader.cs
SharpPcap/LibPcap/PcapUnmanagedStructures.cs

MacOSX's version of [timeval](https://developer.apple.com/documentation/kernel/timeval) uses 
[__darwin_time_t](https://opensource.apple.com/source/xnu/xnu-1228.0.2/bsd/ppc/_types.h) and  [__darwin_suseconds_t](https://opensource.apple.com/source/xnu/xnu-792/bsd/sys/_types.h) types for its fields, which are typedefs for long and int32_t respectively. On MacOSX type of tv_usec therefore differs from type in timeval_unix structure.

Added MacOSX's version of timeval structure.

---

SharpPcap/ICaptureDevice.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Unix.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Windows.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/LibPcap/PcapDevice.cs
SharpPcap/WinPcap/WinPcapDevice.cs

Hi Chris,
first of all I want to thank you for providing and maintaining the SharpPcap library!
We are using your library to develop a monitoring tool for Industrial Communication Networks, such as EtherCAT and PROFINET. 
Next to a Windows based GUI, we are offering a Linux-Version of our tool based on .Net Core.
The capture process works fine, however we had some issues with the KernelBufferSize of LibPcap.
For the type of networks, we analyze, it is required to increase the KernelBufferSize to at least  ~25-50 MB in order to avoid packet losses.
With the current SharpPcap implementation, this is not possible for LibPcapDevices.
Therefore I have made some changes in the SharpPcap, which connect the pcap_set_buffer_size() function to the KernelBufferSize property of the LibPcapDevice …

Proposal for setting KernelBufferSize of LibPcapDevices.

---

SharpPcap/ICaptureDevice.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Unix.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Windows.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/LibPcap/PcapDevice.cs
SharpPcap/SharpPcap.csproj

Two main changes:
* Make SendPacket allocate no memory
* Allow using `Span<byte>` instead of byte[]
---
Zero copy PInvoke logic based on:
https://medium.com/@antao.almada/p-invoking-using-span-t-a398b86f95d3

Allow sending packet using Span<byte>

---

SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapLiveDeviceList.cs
SharpPcap/LibPcap/PcapInterface.cs
SharpPcap/Npcap/NpcapDeviceList.cs
SharpPcap/WinPcap/WinPcapDeviceList.cs

* GetAllNetworkInterfaces is an expensive operation, it cab take up to few milliseconds.
With 10 adapters this function could take up to 200ms.
* The existing code calls GetAllNetworkInterfaces for each pcap device created, this causes a Refresh operation to take seconds (10 * 200ms).
* Calling the constructor of any pcap device implicitly calls GetAllNetworkInterfaces, causing a delay.
* Proposed fix is to have GetAllNetworkInterfaces called once for each refresh operation.
* And creating Pcap device with constructor takes 0s (by simplifying the constructor)

Remove extra calls to GetAllNetworkInterfaces

---

Examples/Example10.SendQueue/Example10.SendQueues.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Unix.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Windows.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/LibPcap/PcapHeader.cs
SharpPcap/LibPcap/SendQueue.cs
SharpPcap/Npcap/SendQueue.cs
SharpPcap/WinPcap/SafeNativeMethods.cs
SharpPcap/WinPcap/SendQueue.cs
Test/SendPacketTest.cs
Test/SendQueueTest.cs
Test/TestHelper.cs

After double checking, I found that the API related to send_queue is no longer windows specific,
Someone has already ported it to libpcap, although no documentation exists for it
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap/pcap.h#L624
As a matter of fact, Windows no longer have any features specific only to it, the entire WinPcap API was merged to Libpcap, and Npcap only provides the driver now.
This PR moves the send_queue logic to the common LibPcap namespace, with cross platform mechanisms to detect if the feature is available or not.
The existing public API has not been changed.
I did not get the chance to test this on Linux/Mac hopefully the Unit Tests would show if there are problems.
@chmorgan how do I see the logs for Linux/Mac in Appveyor?
I added some tests for …

Make SendQueue cross platform

---

SharpPcap/LibPcap/SendQueue.cs
Test/SendQueueTest.cs

Using a `IntPtr.Zero` as a device handle is acceptable in winpcap with send queue, Npcap throws a memory access violation.

Fix IsHardwareAccelerated in Npcap

---

SharpPcap/LibPcap/PcapInterface.cs

On some linux machines, libpcap reports the same MacAddress more than once in the addresses list

Fix duplicate MacAddress exception on Linux

---

.circleci/config.yml
.config/travis/test.sh
SharpPcap/LibPcap/PcapDeviceCaptureLoop.cs
Test/PcapDeviceTest.cs
Test/SendPacketTest.cs
Test/SendQueueTest.cs
Test/TestHelper.cs
azure-pipelines.yml

Fixed problems:
* It seems that using `StartCapture`, and `Send` methods on the same device causes the pcap handle to misbehave due to concurrent thread access.
* Don't throw in StopCapture if Thread.Abort was used
* Don't throw in `[TearDown]` if the test is already failing, otherwise the original failure reason would be lost
* Renew `CancellationTokenSource` during StopCapture since each thread needs its own `CancellationToken`

Fix failing tests

---

SharpPcap/PosixTimeval.cs
SharpPcap/WinDivert/WinDivertAddress.cs
SharpPcap/WinDivert/WinDivertDevice.cs
SharpPcap/WinDivert/WinDivertLayer.cs
SharpPcap/WinDivert/WinDivertNative.cs
SharpPcap/WinDivert/WinDivertParam.cs
Test/WinDivert/WinDivertDeviceTest.cs

WinDivert is a similar driver to WinPcap/Npcap but with a different objectives:
* Only works on network layer (no link layer support)
* Injects itself between the application and the OS, not between the OS and the adapter driver.
* Can cause the OS to drop packets
* Can cause the OS to delay/alter received/sent packets
* Portable (no installation required)
This PR is NOT intended to support all of WinDivert features, instead it focuses on the ones that are common with Libpcap: the ability to sniff packets.
https://www.reqrypt.org/windivert.html

Basic support for WinDivert driver

---

codecov.yml

When one CI service fails for a PR, the coverage comment by Codecov should still show up

Codecov: Tolerate one CI being down

---

scripts/install-libpcap.sh

There was an error in the install script, and it seems it was using master version of Libpcap instead 1.9.1

Use Libpcap 1.9.1 instead of master

---

.appveyor.yml
.travis.yml
Test/Test.csproj
azure-pipelines.yml
scripts/install-dotnet.sh

.Net Core 2.2 reached end of life.
See https://devblogs.microsoft.com/dotnet/net-core-2-2-will-reach-end-of-life-on-december-23-2019/

Upgrade to .Net Core 3.1

---

SharpPcap/RawCapture.cs
SharpPcap/WinDivert/IpHelper.cs
SharpPcap/WinDivert/WinDivertAddress.cs
SharpPcap/WinDivert/WinDivertCapture.cs
SharpPcap/WinDivert/WinDivertDevice.cs
SharpPcap/WinDivert/WinDivertNative.cs
SharpPcap/WinDivert/WinDivertPacket.cs
SharpPcap/WinDivert/WinDivertPacketFlags.cs
Test/WinDivert/WinDivertDeviceTest.cs

Allow sending Packets using WinDivert
@basil00 Could you provide an example/reference how one may be able to find the value of sub-interface ?
All the examples I found mention an interface index, but never a sub-interface index.
Example https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestinterface
The test I made was only for outbound packets, and I verified packets were actually sent using Wireshark
@Zeelize could you use the code in the PR and see if it works correctly for your use case in #140?

Add support for sending with WinDivert

---

.appveyor.yml
.circleci/config.yml
SharpPcap/LibPcap/CaptureFileReaderDevice.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/PcapDevice.cs
SharpPcap/LibPcap/PcapDeviceCaptureLoop.cs
TODO-CI.md
Test/TestHelper.cs
azure-pipelines.yml
scripts/test-travis.sh

* Add polling before calling `pcap_next_ex` in Unix to prevent hanging
* Enable SendPacket tests in CI for all platforms

Fix SendPacket tests in Linux

---

SharpPcap/DeviceConfiguration.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Unix.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Windows.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/PcapError.cs
Test/PcapDeviceTest.cs
Test/RemotePcapTests.cs
Test/TestHelper.cs

@chmorgan I expect some tests to fail on the first run due to platform support (I need them to fail on purpose to see what platform can do what).
regardless a review of the idea/concept would be appreciated.

Add support for more configuration options. Allow detecting partially failed configuration.

---

SharpPcap/DeviceConfiguration.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/Npcap/NpcapDevice.cs
Test/PcapDeviceTest.cs

With this PR, the only thing left that is NpcapDevice specific is Statistics Mode

Move MinToCopy to DeviceConfiguration

---

SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
Test/LibpcapVersionAttribute.cs
Test/PcapDeviceTest.cs
Test/Test.csproj

Usage
```cs
[Test]
[LibpcapVersion(">2.0.0")]
public void LibpcapVersionAttributeTest()
{
// Test will only run if libpcap version > 2.0.0
Assert.Fail("Libpcap coming from the future");
}
```
See https://docs.npmjs.com/cli/v6/using-npm/semver for examples on ranges

Add LibpcapVersionAttribute

---

SharpPcap/LibPcap/PcapInterface.cs
scripts/InstallNpcap.ps1

Add missing offset parameter. Only the first value was read from the list.

Fix parse of pcap_list_tstamp_types

---

SharpPcap/LibPcap/CaptureFileReaderDevice.cs
SharpPcap/LibPcap/CaptureFileWriterDevice.cs
SharpPcap/LibPcap/LibPcapLiveDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Interop.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/LibPcap/PcapDevice.cs
SharpPcap/LibPcap/PcapDeviceCaptureLoop.cs
SharpPcap/LibPcap/PcapHandle.cs
SharpPcap/LibPcap/PcapInterface.cs
SharpPcap/LibPcap/PcapStatistics.cs
SharpPcap/LibPcap/SendQueue.cs
SharpPcap/Statistics/StatisticsDevice.cs
Test/CheckFilterTest.cs
Test/MemorySafetryTests.cs
Test/SendQueueTest.cs

Fixes #295
Same tests that crash in #305 are now passing here.
@KoenPlasmansLS could you test if this PR fixes your problem?
Other handles needs to be updated as well from `IntPtr` to `SafeHandle`, those should be addressed in other PRs otherwise this PR would be too big.
List of handles that needs updating (in the future)
* `pcap_dumper_t *`
* `bpf_program *`
* `pcap_pkthdr *`
* `pcap_stat *`
* `pcap_if_t *`
* `int **tstamp_typesp`

Use SafeHandle

---

.config/dotnet-tools.json
azure-pipelines.yml
codecov.yml
scripts/test.sh

On February 1, 2022, the codecov-bash uploader will be fully sunset and no longer function
https://github.com/codecov/codecov-bash
instead this PR uses https://www.nuget.org/packages/Codecov.Tool/

Better coverage collection

---

.appveyor.yml
azure-pipelines.yml
scripts/Install-npcap.ps1
scripts/install-windows.ps1

* Dropped by Microsoft, see https://github.com/actions/virtual-environments/issues/4312
* With the introduction of VS2022, it makes no sense ton invest time on VS2017 anymore
* VS2017 "Mainstream End Date" is Apr 12, 2022, See https://docs.microsoft.com/en-us/lifecycle/products/visual-studio-2017

Drop Windows 2016 and VS 2017

---

SharpPcap/LibPcap/CaptureFileReaderDevice.cs
SharpPcap/LibPcap/CaptureHandleReaderDevice.cs
SharpPcap/LibPcap/CaptureReaderDevice.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.Interop.cs
SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs
SharpPcap/LibPcap/PcapDeviceCaptureLoop.cs
SharpPcap/LibPcap/PcapHandle.cs
Test/CaptureHandleReaderDeviceTest.cs
Test/Test.csproj

Add a CaptureHandleReaderDevice that can be instantiated with an existing file handle. This is advantageous in situations where one would like fine-grained control over how the handle is opened.

Add support for reading capture data from a file handle

---

SharpPcap/LibPcap/LibPcapLiveDevice.cs

added a check to see if the handle is invalid or not after pcap_create and before the configuration (otherwise a memory access violation can be caused if the adapter was removed or disabled)

add check on invalid handle after pcap_create

---

Tutorial/README.md

fixes https://github.com/dotpcap/sharppcap/issues/483

update tutorial after WinPcapDevice was removed

---

Test/ArpTest.cs
Test/CaptureDeviceListTest.cs
Test/CaptureFileReaderDeviceTest.cs
Test/CaptureFileWriterDeviceTest.cs
Test/CaptureHandleReaderDeviceTest.cs
Test/CheckFilterTest.cs
Test/DeviceFixture.cs
Test/LibPcapLiveDeviceTest.cs
Test/LivePcapDeviceListTest.cs
Test/LivePcapDeviceSetFilterTest.cs
Test/MemorySafetyTests.cs
Test/PcapDeviceTest.cs
Test/PcapStatisticsTest.cs
Test/PcapTest.cs
Test/PosixTimevalTest.cs
Test/RemotePcapTests.cs
Test/SendPacketTest.cs
Test/SendQueueTest.cs
Test/Statistics/StatisticsDeviceTest.cs
Test/Test.csproj
Test/TestHelper.cs
Test/Tunneling/TunnelDeviceTest.cs
Test/Tunneling/UdpTester.cs
Test/WinDivert/IpHelperTest.cs
Test/WinDivert/WinDivertDeviceTest.cs
Test/WinpkFilter/WinpkFilterDeviceTest.cs

See https://docs.nunit.org/articles/nunit/release-notes/Nunit4.0-MigrationGuide.html
[NUnit.Analyzer](https://www.nuget.org/packages/NUnit.Analyzers) was used to perform Assert migration automatically

Update dependency NUnit to v4

---

Test/Tunneling/TunnelDeviceTest.cs

This test has been failing recently at random, put it on retry for now

Retry TestUdpTunnel on failure

---

.appveyor.yml

Spin off #495 
Ubuntu 18.04 already reached end of life (only paid Extended Security Maintenance is available), so it would make sense to just remove Ubuntu from AppVeyor
Reference: https://ubuntu.com/blog/ubuntu-18-04-eol-for-devices
Resolves #396

Remove Ubuntu 18 from appveyor.yml.

---

Test/ThreadSafeTests.cs

Disable it for now (for . NET 8 only), since it's blocking other PRs from being green

Disable Thread Safety Test for .NET 8

---

README.md

Update the examples found in the README. PacketCapture does not have a field or property `Packet` but a method `GetPacket`.

Update README to specify GetPacket not Packet

---

SharpPcap/SharpPcap.csproj

Noticed that SharpPcap had duplicate NuGet packages, possibly they came about after a merge or rebase? Figured it was best to remove them.

Remove duplicate nuget packages in SharpPcap csproj

---

SharpPcap/LibPcap/LibPcapSafeNativeMethods.Resolver.cs
SharpPcap/LibPcap/NativeLibrary.cs
SharpPcap/LibPcap/PcapDevice.cs
SharpPcap/SharpPcap.csproj
SharpPcap/Tunneling/WinTap/WinTapDriver.cs
azure-pipelines.yml

Trimmable Support

---

SharpPcap/WinDivert/WinDivertPacketFlags.cs

```
var x = (WinDivertPacketFlags)167;
Console.WriteLine(x.ToString());
```
Before this change:
```
167
```
After this change
```
Sniffed, Outbound, Loopback, IPChecksum, UDPChecksum
```
This is particularly useful in a debugger. 
Also, it fixes that ReSharper warning

Set FlagsAttribute on WinDivertPacketFlags

---

SharpPcap/LibPcap/Sockaddr.cs

I chose to move the `Math.Min` a bit earlier, this way the `byte[]` allocated is smaller as well.

fix: #518 limit length of hardware address on linux

---

SharpPcap/LibPcap/LibPcapSafeNativeMethods.Encoding.cs

By fixing errbuf returning something, it was missed on several rewrites that the comment was still inside.

remove never used comment

---

SharpPcap/LibPcap/LibPcapLiveDevice.cs

Fix remote PCAP detection logic
